/**
 * ClientDataRoom — documents and files shared with the business owner.
 *
 * A lightweight read-only view of the advisor's Data Room for this company.
 * In the current phase, this is a placeholder with guidance about sharing documents.
 */

import { Folder, FileText, Info } from 'lucide-react'
import { useUserRole } from '../../context/UserRoleContext'
import { usePageTitle } from '../../hooks/usePageTitle'
import SectionHeader from '../../components/ui/SectionHeader'

export default function ClientDataRoom() {
  usePageTitle('Documents')
  const { clientCompany } = useUserRole()

  return (
    <div className="max-w-3xl mx-auto space-y-6">
      <SectionHeader
        icon={<Folder className="w-5 h-5" />}
        title="Documents"
        subtitle={`Files and reports shared by your advisor for ${clientCompany?.name ?? 'your company'}.`}
      />

      {/* Placeholder */}
      <div className="bg-card rounded-xl border border-border p-12 text-center">
        <Folder className="w-12 h-12 text-muted-foreground/40 mx-auto mb-4" />
        <h3 className="text-base font-semibold text-card-foreground mb-2">No documents yet</h3>
        <p className="text-sm text-muted-foreground max-w-sm mx-auto leading-relaxed">
          Your advisor will share reports, analyses, and key documents here as the engagement progresses.
        </p>
      </div>

      {/* Info note */}
      <div className="bg-card rounded-xl border border-border p-5">
        <div className="flex items-center gap-2 mb-3">
          <Info className="w-4 h-4 text-muted-foreground" />
          <h3 className="text-sm font-semibold text-card-foreground">What to Expect Here</h3>
        </div>
        <ul className="space-y-2 text-sm text-muted-foreground">
          {[
            'Diligence Readiness Reports (PDF) generated by your advisor',
            'Valuation analyses and enterprise value estimates',
            'Initiative roadmaps and value-creation plans',
            'Key company documents uploaded for the virtual data room',
          ].map((item) => (
            <li key={item} className="flex items-start gap-2">
              <FileText className="w-3.5 h-3.5 text-primary flex-shrink-0 mt-0.5" />
              {item}
            </li>
          ))}
        </ul>
      </div>
    </div>
  )
}
