// Static reference data for ABC Company Inc — Field Services / Traffic Management
// Live analytics values come from API; these are fallbacks and UI-only fields

export const company = {
  id: 'abc-company-001',
  name: 'ABC Company Inc',
  initials: 'AC',
  industry: 'Field Services — Traffic Management & Transportation',
  employees: 25,
  founded: 2009,
  status: 'Active Engagement',
  stage: 'Pre-Diligence',
}

// Baseline fallback values — overridden by live API data where available
export const kpis = {
  drs: 72,
  drsPercentile: 78,
  ebitda: 1_743_357,
  ebitdaMultiple: 5.62,
  currentEV: 9_810_000,
  potentialEV: 11_320_000,
  valueGap: 1_510_000,
  ttmRevenue: 4_196_172,
  revenueGrowthYoY: 18.7,
  recurringRevenuePct: 0,
  grossMargin: 44.4,
  payrollRatio: 29.2,
}

export const drsCategories = [
  { name: 'Revenue Quality',          score: 70, weight: 0.25, tier: 'Investment' },
  { name: 'Financial Integrity',      score: 74, weight: 0.20, tier: 'Investment' },
  { name: 'Operational Independence', score: 71, weight: 0.20, tier: 'Investment' },
  { name: 'Customer Risk',            score: 70, weight: 0.15, tier: 'Investment' },
  { name: 'Management & Team',        score: 72, weight: 0.10, tier: 'Investment' },
  { name: 'Growth Drivers',           score: 78, weight: 0.10, tier: 'Investment' },
]

export const ebitdaRecast = {
  reportedNetIncome: 1_743_357,
  addbackDA: 0,
  addbackInterest: 0,
  addbackTaxes: 0,
  reportedEBITDA: 1_743_357,
  addbackOwnerComp: 82_221,
  addbackPersonal: 0,
  addbackNonRecurring: 0,
  defensibleEBITDA: 1_825_578,
  scenarios: {
    conservative: 1_680_000,
    base: 1_825_578,
    aggressive: 1_950_000,
  },
}

export const customerConcentration = [
  { name: 'COMPANY 1',    revenuePct: 49.4, revenue: 2_072_865, contractStatus: 'Active', tenure: 9.0 },
  { name: 'COMPANY 2',    revenuePct: 19.0, revenue:   796_991, contractStatus: 'Active', tenure: 9.0 },
  { name: 'COMPANY 3',    revenuePct:  4.9, revenue:   205_694, contractStatus: 'Active', tenure: 8.0 },
  { name: 'COMPANY 4',    revenuePct:  3.3, revenue:   138_502, contractStatus: 'Active', tenure: 8.0 },
  { name: 'COMPANY 5',    revenuePct:  2.4, revenue:   100_691, contractStatus: 'Active', tenure: 7.0 },
  { name: 'Others (63)',  revenuePct: 21.0, revenue:   881_429, contractStatus: 'Mixed',  tenure: null },
]

export const monthlyRevenue = [
  { month: "Jan '25", revenue: 349_681 },
  { month: "Feb '25", revenue: 349_681 },
  { month: "Mar '25", revenue: 349_681 },
  { month: "Apr '25", revenue: 349_681 },
  { month: "May '25", revenue: 349_681 },
  { month: "Jun '25", revenue: 349_681 },
  { month: "Jul '25", revenue: 349_681 },
  { month: "Aug '25", revenue: 349_681 },
  { month: "Sep '25", revenue: 349_681 },
  { month: "Oct '25", revenue: 349_681 },
  { month: "Nov '25", revenue: 349_681 },
  { month: "Dec '25", revenue: 349_681 },
]

export const valueCreationLevers = [
  { rank: 1, initiative: 'Customer Concentration',    valueMin: 600_000,  valueMax: 1_000_000, detail: 'Top 2 customers = 68.4% of revenue. Reduce below 40% to move from PRE_DILIGENCE to HIGH_RISK tier', timeline: '24mo', severity: 'high' },
  { rank: 2, initiative: 'Contract Formalization',    valueMin: 400_000,  valueMax: 800_000,   detail: 'Project-based relationships lack MSAs. Contractualize top 10 accounts to increase revenue quality score', timeline: '6mo',  severity: 'high' },
  { rank: 3, initiative: 'Key Person Dependency',     valueMin: 300_000,  valueMax: 600_000,   detail: 'Owner drives all customer relationships and field ops. Hire operations manager and document processes', timeline: '12mo', severity: 'high' },
  { rank: 4, initiative: 'Financial Documentation',   valueMin: 150_000,  valueMax: 350_000,   detail: 'No CPA review or audit. Engage CPA for 3-year review to support buyer financial integrity score', timeline: '3mo',  severity: 'medium' },
  { rank: 5, initiative: 'Revenue Diversification',   valueMin: 200_000,  valueMax: 500_000,   detail: 'Add 15+ new customers at $80K+ each to reduce HHI from 2,472 to below 1,500', timeline: '18mo', severity: 'medium' },
  { rank: 6, initiative: 'EBITDA Margin Improvement', valueMin: 100_000,  valueMax: 250_000,   detail: 'EBITDA margin ~41.5%. Further reduce equipment rental and overtime through fleet ownership and scheduling', timeline: '12mo', severity: 'medium' },
]

export const advisoryWorkflowStages = [
  { stage: 1, name: 'Discovery',              status: 'complete',     progress: 100 },
  { stage: 2, name: 'Data Collection',        status: 'complete',     progress: 100 },
  { stage: 3, name: 'Financial Analysis',     status: 'complete',     progress: 100 },
  { stage: 4, name: 'Business Valuation',     status: 'complete',     progress: 100 },
  { stage: 5, name: 'Value Gap Analysis',     status: 'in_progress',  progress: 40 },
  { stage: 6, name: 'Risk Mitigation Plan',   status: 'pending',      progress: 0 },
  { stage: 7, name: 'Buyer Readiness',        status: 'pending',      progress: 0 },
  { stage: 8, name: 'Process Preparation',    status: 'pending',      progress: 0 },
  { stage: 9, name: 'Exit Execution',         status: 'pending',      progress: 0 },
]

export const engagementTimeline = [
  {
    id: 1,
    milestone: 'Onboarding',
    date: 'Jan 15, 2025',
    stage: 'onboarding',
    status: 'complete',
    drs: null,
    drs_tier: null,
    ebitda: null,
    ev_floor: null,
    ev_ceiling: null,
    ev_midpoint: null,
    multiple_floor: null,
    multiple_ceiling: null,
    notes: 'Initial engagement signed. Financial data package requested. Owner debrief complete — 25 employees, field services, $4M+ revenue base.',
  },
  {
    id: 2,
    milestone: 'Data Ingestion',
    date: 'Feb 3, 2025',
    stage: 'data_collection',
    status: 'complete',
    drs: null,
    drs_tier: null,
    ebitda: 1_743_357,
    ev_floor: null,
    ev_ceiling: null,
    ev_midpoint: null,
    multiple_floor: null,
    multiple_ceiling: null,
    notes: '3 years QuickBooks P&L, payroll register, and customer data ingested. Reported EBITDA proxy: ~$1.74M. Gross margin ~44%.',
  },
  {
    id: 3,
    milestone: 'Baseline Valuation',
    date: 'Feb 14, 2025',
    stage: 'baseline',
    status: 'complete',
    drs: 72.0,
    drs_tier: 'INVESTMENT',
    ebitda: 1_743_357,
    ev_floor: 8_320_000,
    ev_ceiling: 11_320_000,
    ev_midpoint: 9_810_000,
    multiple_floor: 4.8,
    multiple_ceiling: 6.5,
    notes: 'INVESTMENT tier with blended DRS (5.0x–7.0x) and curated field_services market band (4.55x–6.0x). EV midpoint ~$9.81M on normalized EBITDA.',
  },
  {
    id: 4,
    milestone: 'EBITDA Recast',
    date: 'Mar 1, 2025',
    stage: 'ebitda_recast',
    status: 'complete',
    drs: 72.0,
    drs_tier: 'INVESTMENT',
    ebitda: 1_825_578,
    ev_floor: 8_700_000,
    ev_ceiling: 11_850_000,
    ev_midpoint: 10_275_000,
    multiple_floor: 4.8,
    multiple_ceiling: 6.5,
    notes: 'Owner comp normalized to market rate ($120K vs $202K actual). ~$82K addback. Defensible EBITDA ~$1.83M; EV midpoint moves up modestly.',
  },
  {
    id: 5,
    milestone: 'Value Gap Analysis',
    date: 'Mar 27, 2025',
    stage: 'value_gap',
    status: 'current',
    drs: 72.0,
    drs_tier: 'INVESTMENT',
    ebitda: 1_825_578,
    ev_floor: 8_700_000,
    ev_ceiling: 11_850_000,
    ev_midpoint: 10_275_000,
    multiple_floor: 4.8,
    multiple_ceiling: 6.5,
    notes: 'Value levers focus on concentration, contract formalization, and documentation — upside to ceiling multiple band on execution.',
  },
  {
    id: 6,
    milestone: '90-Day Quick Wins',
    date: 'Jun 15, 2025',
    stage: 'projected_90d',
    status: 'projected',
    drs: 74.0,
    drs_tier: 'INVESTMENT',
    ebitda: 1_880_000,
    ev_floor: 9_020_000,
    ev_ceiling: 12_200_000,
    ev_midpoint: 10_610_000,
    multiple_floor: 4.8,
    multiple_ceiling: 6.5,
    notes: 'Projected upon MSAs with top accounts, CPA review sign-off, and KPI dashboard deployment.',
  },
  {
    id: 7,
    milestone: 'Investment Grade Target',
    date: 'Q1 2027',
    stage: 'target',
    status: 'projected',
    drs: 78.0,
    drs_tier: 'INVESTMENT',
    ebitda: 2_050_000,
    ev_floor: 10_250_000,
    ev_ceiling: 14_350_000,
    ev_midpoint: 12_300_000,
    multiple_floor: 5.0,
    multiple_ceiling: 7.0,
    notes: 'Target upon resolving high-priority initiatives: customer concentration <40%, stronger recurring mix, documented ops.',
  },
]

export const recentActivity = [
  { event: 'DRS scored: 72.0/100 — Investment tier',                  detail: 'Blended category scores; recurring revenue still a focus area.', time: 'Mar 27' },
  { event: 'QuickBooks P&L ingested — 3 fiscal years',               detail: '2023: $2.79M — 2024: $2.75M — 2025: $4.20M — EBITDA proxy ~$1.74M — gross margin ~44%', time: 'Mar 27' },
  { event: 'EBITDA recast — Officers salary addback $82K',   detail: '$202,221 actual vs $120,000 market rate — defensible EBITDA ~$1.83M', time: 'Mar 27' },
  { event: 'EV range ~$8.3M–$11.3M (mid ~$9.81M)',   detail: 'Blended DRS + field_services $1M–$5M market band. TTM: COMPANY 1 = 49.4%, top-2 = 68.4%', time: 'Mar 27' },
]

